app.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.when('','/index');
    $stateProvider
    .state({
        name:'index',
        url:'/index',
        views:{
            'nav':{
                templateUrl:"../views/public/nav.html",
                controller: 'indexCtrl'
            },
            'banner':{
                templateUrl:"../views/public/banner.html"
            },
            'content':{
                templateUrl:"../views/index.html",
                controller: 'indexCtrl'
            },
            'footer':{
                templateUrl:"../views/public/footer.html"
            },
        }
    })
    .state({
        name:'index.news',
        url:'/news',
        views:{
            'content@':{
                templateUrl:"../views/news.html",
                controller: 'newsCtrl'
            },
        }
    })
    .state({
        name:'index.news.detail',
        url:'/detail',
        views:{
            'content@':{
                templateUrl:"../views/news-con.html"
            },
        }
    })
    .state({
        name:'index.pinpai',
        url:'/pinpai',
        views:{
            'content@':{
                templateUrl:"../views/pinpai.html",
                controller: 'singleCtrl'
            },
        }
    })
    .state({
        name:'index.pinpai.detail',
        url:'/detail',
        views:{
            'content@':{
                templateUrl:"../views/pinpai-con.html"
            },
        }
    })
    .state({
        name:'index.meishi',
        url:'/meishi',
        views:{
            'content@':{
                templateUrl:"../views/meishi.html",
                controller: 'foodCtrl'
            },
        }
    })
    .state({
        name:'index.meishi.detail',
        url:'/detail',
        views:{
            'content@':{
                templateUrl:"../views/meishi-con.html"
            },
        }
    })
    .state({
        name:'index.shop',
        url:'/shop',
        views:{
            'content@':{
                templateUrl:"../views/shop.html",
                controller: 'shopCtrl'
            },
        }
    })
    .state({
        name:'index.shop.detail',
        url:'/detail',
        views:{
            'content@':{
                templateUrl:"../views/shop-con.html"
            },
        }
    })
    .state({
        name:'index.about',
        url:'/about',
        views:{
            'content@':{
                templateUrl:"../views/about-us.html",
                controller: 'indexCtrl'
            },
        }
    })
}).run()